spring:
  application:
    name: hello-service

grpc:
  port: 8080
eureka:
  instance:
    nonSecurePort: ${grpc.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/